# ruta: finanzas/mysite/settings.py
"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga las variables definidas en un archivo .env (en la raíz del
# proyecto, junto a manage.py) hacia el entorno del proceso. Si el
# archivo no existe simplemente no hace nada, así que es seguro tenerlo
# en producción también (ahí las variables ya vienen del hosting).
load_dotenv(BASE_DIR / ".env")

# Render define esta variable automáticamente en los servicios web (con el
# dominio público, ej. mi-app.onrender.com). En tu PC no existe, así que sirve
# para saber si la app está corriendo en producción (Render) o en local.
RENDER_HOST = os.environ.get("RENDER_EXTERNAL_HOSTNAME")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", 'django-insecure-*b$8ub+coqm1j)-0q(8gl1et7a*fe&44+v&53j+lb8_ng=*a80')

# SECURITY WARNING: don't run with debug turned on in production!
# En tu PC: DEBUG activo. En Render (producción): apagado.
DEBUG = not RENDER_HOST

ALLOWED_HOSTS = [RENDER_HOST] if RENDER_HOST else []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "cuentas",
    "tasas",
    "ia",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}



# ---------------------------------------------------------------------
# Microservicios (con resiliencia)
# ---------------------------------------------------------------------
# Los cuatro microservicios hacen lo mismo (tasas, IA, insertar, actualizar
# y eliminar cuentas). Django los prueba EN ESTE ORDEN: si el primero falla,
# pasa al segundo, luego al tercero y por último al cuarto
# (ver mysite/microservicios.py). Un servicio con URL vacía se salta.
# Las URLs van sin "/" al final, por ejemplo https://mi-servicio.onrender.com
MICROSERVICIOS = [
    {"nombre": "Python", "url": os.environ.get("MS_PYTHON_URL", "https://app-finanzas-hqu1.onrender.com")},
    {"nombre": "Java", "url": os.environ.get("MS_JAVA_URL", "https://app-finanzas-1-f26s.onrender.com")},
    {"nombre": "Node.js", "url": os.environ.get("MS_NODE_URL", "https://app-finanzas-2-mw1d.onrender.com")},
    {"nombre": "Go", "url": os.environ.get("MS_GO_URL", "https://app-finanzas-3.onrender.com")},
]

# Segundos de espera por servicio antes de pasar al siguiente.
# Lectura: el usuario está esperando la página, así que es más corto.
# Escritura: corre en segundo plano, así que damos más margen (los servicios
# gratis de Render tardan en "despertar" si llevaban rato sin usarse).
MS_TIMEOUT_LECTURA = int(os.environ.get("MS_TIMEOUT_LECTURA", "15"))
MS_TIMEOUT_ESCRITURA = int(os.environ.get("MS_TIMEOUT_ESCRITURA", "45"))


# ---------------------------------------------------------------------
# Producción (Render)
# ---------------------------------------------------------------------
# Base de datos: si existe la variable DATABASE_URL (Render la recibe desde su
# PostgreSQL) se usa esa base; si no, sigue usando el SQLite local de siempre.
# Esto es necesario porque el disco de Render gratis se borra al reiniciar,
# y un archivo SQLite ahí perdería tus cuentas.
DATABASE_URL = os.environ.get("DATABASE_URL")
if DATABASE_URL:
    import dj_database_url

    DATABASES = {"default": dj_database_url.parse(DATABASE_URL, conn_max_age=600)}

if RENDER_HOST:
    # WhiteNoise sirve los archivos estáticos (CSS del admin, etc.) desde Django.
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")
    STATIC_ROOT = BASE_DIR / "staticfiles"
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
    }
    # Para que los formularios (POST) funcionen por https detrás del proxy de Render.
    CSRF_TRUSTED_ORIGINS = [f"https://{RENDER_HOST}"]
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")