# ruta: finanzas/mysite/settings.py
"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga las variables definidas en un archivo .env (en la raíz del
# proyecto, junto a manage.py) hacia el entorno del proceso. Si el
# archivo no existe simplemente no hace nada, así que es seguro tenerlo
# en producción también (ahí las variables ya vienen del hosting).
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*b$8ub+coqm1j)-0q(8gl1et7a*fe&44+v&53j+lb8_ng=*a80'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "cuentas",
    "tasas",
    "ia",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}



# ---------------------------------------------------------------------
# Microservicios (con resiliencia)
# ---------------------------------------------------------------------
# Los cuatro microservicios hacen lo mismo (tasas, IA, insertar, actualizar
# y eliminar cuentas). Django los prueba EN ESTE ORDEN: si el primero falla,
# pasa al segundo, luego al tercero y por último al cuarto
# (ver mysite/microservicios.py). Un servicio con URL vacía se salta.
# Las URLs van sin "/" al final, por ejemplo https://mi-servicio.onrender.com
MICROSERVICIOS = [
    {"nombre": "Python", "url": os.environ.get("MS_PYTHON_URL", "https://app-finanzas-hqu1.onrender.com")},
    {"nombre": "Java", "url": os.environ.get("MS_JAVA_URL", "")},
    {"nombre": "Node.js", "url": os.environ.get("MS_NODE_URL", "")},
    {"nombre": "Go", "url": os.environ.get("MS_GO_URL", "")},
]

# Segundos de espera por servicio antes de pasar al siguiente.
# Lectura: el usuario está esperando la página, así que es más corto.
# Escritura: corre en segundo plano, así que damos más margen (los servicios
# gratis de Render tardan en "despertar" si llevaban rato sin usarse).
MS_TIMEOUT_LECTURA = int(os.environ.get("MS_TIMEOUT_LECTURA", "15"))
MS_TIMEOUT_ESCRITURA = int(os.environ.get("MS_TIMEOUT_ESCRITURA", "45"))