# ruta: finanzas/cuentas/migrations/0003_syncpendiente.py
# Generated by Django 6.1.1 on 2026-09-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_editar_eliminar_y_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=10)),
                ('ruta', models.CharField(max_length=200)),
                ('cuerpo', models.JSONField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('ultimo_error', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]